@ParametersAreNonnullByDefault
@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
package modularmachines.common.modules.components.process.criteria;

import javax.annotation.ParametersAreNonnullByDefault;

import modularmachines.common.utils.FieldsAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;