package modularmachines.common.modules.container.components;

import net.minecraft.nbt.NBTTagCompound;

import net.minecraftforge.energy.EnergyStorage;

import modularmachines.api.modules.INBTReadable;
import modularmachines.api.modules.INBTWritable;

public class EnergyComponent extends EnergyStorage implements INBTWritable, INBTReadable {
	public EnergyComponent(int maxTransfer, int capacity) {
		super(capacity, maxTransfer, maxTransfer);
	}
	
	public void readFromNBT(NBTTagCompound nbt) {
		final int energy = nbt.getInteger("Energy");
		
		setEnergyStored(energy);
	}
	
	public NBTTagCompound writeToNBT(NBTTagCompound nbt) {
		nbt.setInteger("Energy", energy);
		return nbt;
	}
	
	public int getMaxEnergyReceived() {
		return this.maxReceive;
	}
	
	/**
	 * Drains an amount of energy, due to decay from lack of work or other factors
	 */
	public void drainEnergy(int amount) {
		setEnergyStored(energy - amount);
	}
	
	/**
	 * Creates an amount of energy, generated by engines
	 */
	public void generateEnergy(int amount) {
		setEnergyStored(energy + amount);
	}
	
	public void setEnergyStored(int energyStored) {
		this.energy = energyStored;
		if (this.energy > capacity) {
			this.energy = capacity;
		} else if (this.energy < 0) {
			this.energy = 0;
		}
	}
	
}